### ISSUE TITLE
Maybe delete this list?

### ISSUE THREAD

**Issue by sdegutis** [ElDragonRojo/good#22]
You know, for the sake of the rest of us, who never made it on this list purely because we're nobodies?

**Comment by ElDragonRojo** [comment]
That's an interesting viewpoint, but it presupposes being on the this list means anything but that I think I met you, think I remember you, and don't think I think you are an asshole. 

Really, there are much, much bigger problems with this format than that, but I don't think the solution is to nuke it from orbit, but rather to continue to evolve the idea (this list not actually being the first iteration of this idea) to meet those challenges. Now that the shouting has stopped I am starting to think about these things again.

Thank you, as always, for your participation and advice.

**Comment by sdegutis** [comment]
No problem. Thanks for reading my request and responding.
